'use client';
import {useEffect,useRef,useState} from 'react';
import {Search,ScanLine,Plus,ArrowRight,Camera,Users,Clock,Check,MapPin,ImageIcon,RefreshCw,Copy,Trash2,ShieldCheck,ArrowUpRight,LoaderCircle,CircleHelp,FolderOpen,Coins} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {extract,excludeAndRefill,type FrameSelection} from '@/lib/media';
import {visionReserve} from '@/lib/vision-config';
type Capture={id:string;label:string;created:string;frames:{id:string;time:number}[];objects:any[];mode:string;canDelete:boolean};
type Data={spaces:{id:string;name:string;isOwner:boolean}[];captures:Capture[];members:number;invite:string;feedback:any[];budget:{total:number;unconfirmed:number;limit:number;cap:number};aiReady:boolean};
const empty:Data={spaces:[],captures:[],members:0,invite:'',feedback:[],budget:{total:0,unconfirmed:0,limit:4.5,cap:4.5},aiReady:false};
const money=(n:number)=>'$'+Number(n||0).toFixed(4);
const date=(s:string)=>new Date(s).toLocaleString('ja-JP',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const imageUrl=(id:string)=>'/api/image?id='+encodeURIComponent(id);
async function post(body:any){const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'操作を完了できませんでした。');return data;}
export default function Workspace({displayName}:{displayName:string}){
const [data,setData]=useState<Data>(empty),[space,setSpace]=useState(''),[tab,setTab]=useState('search'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
const [orgName,setOrgName]=useState(''),[budgetInput,setBudgetInput]=useState(''),[code,setCode]=useState(''),[query,setQuery]=useState(''),[results,setResults]=useState<any[]|null>(null),[elapsed,setElapsed]=useState(0),[cost,setCost]=useState(0),[mode,setMode]=useState(''),[selected,setSelected]=useState<any>(null),[intent,setIntent]=useState(''),[recorded,setRecorded]=useState(false),[apiInput,setApiInput]=useState(''),[editLabel,setEditLabel]=useState(''),[editNotes,setEditNotes]=useState('');
const [selection,setSelection]=useState<FrameSelection>({frames:[],reserve:[]}),[progress,setProgress]=useState(0),[label,setLabel]=useState(''),[notes,setNotes]=useState(''),[shotAt,setShotAt]=useState(()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}),[captureId,setCaptureId]=useState(''),[saving,setSaving]=useState(false);
const [rechecking,setRechecking]=useState<Capture|null>(null);
const [searchReceipt,setSearchReceipt]=useState(''),[confirmedResult,setConfirmedResult]=useState('');
const frames=selection.frames;
const input=useRef<HTMLInputElement>(null),photo=useRef<HTMLInputElement>(null),searchStart=useRef(0),currentSpace=useRef('');
async function load(target=space){const r=await fetch('/api/workspace'+(target?'?space='+encodeURIComponent(target):''));const v=await r.json();if(!r.ok)throw new Error(v.error);setData(v);return v as Data;}
useEffect(()=>{(async()=>{const fragment=new URLSearchParams(location.hash.slice(1));const token=fragment.get('manage')||fragment.get('invite');if(token){history.replaceState(null,'',location.pathname);await post({action:'login',token});}const v=await load('');if(v.spaces.length)setSpace(v.spaces[0].id);})().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
useEffect(()=>{currentSpace.current=space;setSearchReceipt('');setConfirmedResult('');setResults(null);setCaptureId('');setSelection({frames:[],reserve:[]});setLabel('');setNotes('');setError('');if(space)load(space).catch(e=>setError(e.message));},[space]);
async function run(name:string,fn:()=>Promise<void>){setBusy(name);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'処理できませんでした。');}finally{setBusy('');}}
async function join(){await run('join',async()=>{await post({action:'login',token:code});const v=await load('');if(v.spaces.length)setSpace(v.spaces[0].id);setCode('');});}
async function choose(files:File[]){await run('extract',async()=>{setProgress(0);const f=await extract(files,setProgress);setSelection(f);setCaptureId('');setNotice(`${f.frames.length}枚の画像を抽出しました。保存前に確認してください。`);});}
async function save(){setSaving(true);await run('save',async()=>{let id=captureId;if(!id){const r=await post({action:'save',space,label,notes,frames:frames.map(({data,time})=>({data,time})),capturedAt:new Date(shotAt).toISOString()});id=r.id;setCaptureId(id);await load();}if(data.aiReady){setBusy('analyze');const a=await post({action:'analyze',space,capture:id});setNotice(`保存・AI解析が完了しました。${a.objects.length}件の候補 / 概算 ${money(a.cost)}`);}else setNotice('撮影を保存しました。AI未接続のため、入力したメモを検索できます。');await load();setSelection({frames:[],reserve:[]});setCaptureId('');setLabel('');setNotes('');});setSaving(false);}
async function search(q=query){setSearchReceipt('');setConfirmedResult('');await run('search',async()=>{searchStart.current=performance.now();const r=await post({action:'search',space,query:q});setResults(r.results);setElapsed((performance.now()-searchStart.current)/1000);setCost(r.cost);setMode(r.mode);setRecorded(false);});}
async function reanalyze(c:Capture){if(busy||rechecking)return;setSearchReceipt('');setConfirmedResult('');setRechecking(c);try{await run('reanalyze',async()=>{searchStart.current=performance.now();const r=await post({action:'analyze',space,capture:c.id,query});setResults(r.objects.map((o:any)=>({...o,capture:c.id,label:c.label,created:c.created,image:c.frames[o.frame]?.id,time:c.frames[o.frame]?.time})));setElapsed((performance.now()-searchStart.current)/1000);setCost(r.cost);setMode(`「${c.label}」（${date(c.created)}撮影）の画像を再検索`);setSearchReceipt(r.receipt||'');setConfirmedResult(r.objects.length===1?'0':'');if(r.receipt)setNotice('検索語はまだ保存していません。実物を確認し、「実物を見つけた」を押すと追加します。');setRecorded(false);await load();});}finally{setRechecking(null);}}
async function feedback(found:boolean){await run('feedback',async()=>{const r=await post({action:'feedback',space,found,intent,receipt:searchReceipt,resultIndex:confirmedResult===''?null:Number(confirmedResult),seconds:(performance.now()-searchStart.current)/1000});setRecorded(true);setSearchReceipt('');setNotice(r.learned?'実物の発見を記録し、選んだ画像に検索語を追加しました。':'体験の記録を保存しました。');await load();});}
const selectedCapture=selected?.canEdit?data.captures.find(c=>c.id===selected.capture):undefined;
async function deleteFrame(c:Capture,image:string){await run('deleteFrame',async()=>{await post({action:'deleteFrame',space,capture:c.id,image});setResults(null);const updated=await load();const record=updated.captures.find(r=>r.id===c.id);if(!record){setSelected(null);return;}setSelected((v:any)=>v?.capture===c.id?{...v,image:record.frames.some(f=>f.id===v.image)?v.image:record.frames[0].id,description:'保存された撮影画像'}:v);setNotice('画像と、その画像に対応するAIの検索情報を削除しました。');});}
const current=data.spaces.find(s=>s.id===space),totalObjects=data.captures.reduce((n,c)=>n+c.objects.length,0);
useEffect(()=>{setOrgName(current?.name||'');setBudgetInput(String(data.budget.limit));},[current?.id,current?.name,data.budget.limit]);
return <div className="app-shell"><header className="topbar"><a href="/" className="brand"><span className="brand-mark"><ScanLine size={23}/></span><span>ありか<small>SPACE MEMORY</small></span></a><div className="top-right"><span className="prototype">HUMAN TIME HACK · MOCK</span><span className="account"><ShieldCheck size={16}/><span>{displayName}</span></span></div></header>
<div className="main-layout"><aside className="rail"><div className="rail-heading">共有スペース</div>{data.spaces.length>0&&<Select value={space} onValueChange={setSpace} disabled={!!busy}><SelectTrigger className="space-select"><SelectValue placeholder="スペースを選択"/></SelectTrigger><SelectContent>{data.spaces.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select>}
<div className="rail-note"><Users size={17}/><span>{space?'招待リンクで共有':'招待リンクを開いてください'}<small>追加・変更・削除は作成者のみ</small></span></div>
{!space&&<div className="space-actions"><label htmlFor="joincode">招待コード</label><div className="inline"><Input id="joincode" placeholder="招待コードを入力" value={code} onChange={e=>setCode(e.target.value)} autoCapitalize="none" autoCorrect="off"/><Button aria-label="共有スペースを開く" onClick={join} disabled={!!busy||!code.trim()} size="icon"><ArrowRight size={18}/></Button></div></div>}
<div className="budget-box"><div><Coins size={16}/> AI利用料の概算</div><strong>{money(data.budget.total)}<span> / {money(data.budget.limit)}</span></strong><Progress value={data.budget.limit>0?Math.min(100,data.budget.total/data.budget.limit*100):100}/><p>この設置環境の累計です。仮確保を含めて上限を超えるAI処理を停止します。</p>{data.budget.unconfirmed>0&&<p>使用量が未確定のAI呼び出しは、画像3枚ごとに$0.05を仮計上しています。</p>}<span className={data.aiReady?'status-ready':'status-pending'}>{data.aiReady?'AI接続設定済み':'AI未接続 · 保存・メモ検索は利用可'}</span></div>
<Button className="logout" variant="ghost" onClick={()=>run('logout',async()=>{await post({action:'logout'});location.reload();})}>この端末のアクセスを解除</Button></aside>
<main className="workspace"><div className="workspace-top"><div><p className="eyebrow">{current?.name||'YOUR SHARED MEMORY'}</p><h1>探す時間を、<span>つくる時間へ。</span></h1></div>{current?.isOwner&&<Button onClick={()=>setTab('capture')} disabled={!!busy}><Camera size={18}/>空間を記録</Button>}</div>
{error&&<div role="alert" className="message error">{error}{captureId&&' 撮影画像は保存済みです。下の記録一覧からAI解析を再試行できます。'}</div>}{notice&&<div role="status" className="message success">{notice}</div>}{current?.isOwner&&!data.aiReady&&<div className="message setup-notice"><p>APIキーは未設定です。撮影の保存・閲覧と、手動メモの検索から始められます。</p><Button variant="outline" onClick={()=>setTab('share')}>組織名・AI接続・予算を設定</Button></div>}
{loading?<div className="empty-state"><LoaderCircle className="spin"/><p>共有スペースを読み込んでいます</p></div>:!space?<div className="welcome"><span className="large-icon"><ScanLine size={40}/></span><h2>ひとりの記憶を、みんなの手がかりに。</h2><p>招待リンクから開くか、招待コードを入力してください。<br/>動画や写真に映ったモノを、撮影した人以外も探せます。</p><div className="flow"><span><Camera/>撮影する</span><span><Search/>モノを探す</span><span><ArrowUpRight/>仕事に戻る</span></div></div>:<Tabs value={tab} onValueChange={setTab}><TabsList className="main-tabs" variant="line"><TabsTrigger value="search"><Search/>探す</TabsTrigger><TabsTrigger value="capture"><Camera/>記録</TabsTrigger><TabsTrigger value="share"><Users/>共有・設定</TabsTrigger><TabsTrigger value="impact"><Clock/>体験の記録</TabsTrigger></TabsList>
<TabsContent value="search"><section className="search-panel"><p className="section-kicker">何を探していますか？</p><form onSubmit={e=>{e.preventDefault();search();}} className="search-form"><Search/><Input aria-label="探したいモノ" placeholder="例：黒いマイク、椅子、机の上のケーブル" value={query} onChange={e=>setQuery(e.target.value)} maxLength={180}/><Button type="submit" disabled={!!busy||!query.trim()}>{busy==='search'?<LoaderCircle className="spin"/>:'探す'}<ArrowRight size={18}/></Button></form><div className="search-meta"><span>{data.captures.length}件の撮影記録 · {totalObjects}件の手がかり</span><span><ShieldCheck size={14}/>スペース内のみ検索</span></div><p className="subtle">{data.aiReady?'まず保存済みの名前・別名・特徴・位置メモを検索します。見つからない場合は、撮影画像をAIで再確認できます。':'保存済みの手動メモを検索できます。画像の内容を自動で記録・検索するには、管理者によるAPIキーの設定が必要です。'}</p></section>
{results!==null?<><div className="results-heading"><h2>{results.length?`${results.length}件の手がかり`:'撮影記録から特定できませんでした'}</h2><span>{elapsed.toFixed(1)}秒 · AI {money(cost)}</span></div><p className="subtle">{mode}。表示するのは撮影時点の記録です。モノが移動している可能性があります。</p>{!results.length&&<div className="no-result"><CircleHelp size={32}/><p>今回の撮影動画からは、対象の特定に至りませんでした。<br/>角度を変えるか、近づいて再撮影してください。</p></div>}<div className="result-grid">{results.map((r,i)=><button className="result-card" key={i} onClick={()=>setSelected(r)}><div className="result-image"><img src={imageUrl(r.image)} alt={`${r.name}の根拠画像`}/>{r.box&&<span className="object-box" style={{left:r.box[0]*100+'%',top:r.box[1]*100+'%',width:(r.box[2]-r.box[0])*100+'%',height:(r.box[3]-r.box[1])*100+'%'}}/>}<span className="image-tag">{r.source==='手動'?'撮影者のメモ':'AI候補'}</span></div><div className="result-body"><h3>{r.name}<ArrowUpRight size={18}/></h3><p>{r.description}</p><div><MapPin size={14}/>{r.location||r.label}</div><small>{r.label} · {date(r.created)}撮影</small></div></button>)}</div>
<div className="recheck"><div><h3>画像そのものから、もう一度探す</h3><p>検索する撮影記録を1件選んでください。その記録に保存された画像をAIで再確認します。画像3枚ごとに$0.05を仮確保し、使用量で精算します。</p></div><div className="recheck-options" data-searching={!!rechecking}>{data.captures.slice(0,5).map(c=><Button key={c.id} variant="outline" className="recheck-option" data-active={rechecking?.id===c.id} aria-busy={rechecking?.id===c.id} disabled={!!busy||!data.aiReady||!!rechecking} onClick={()=>reanalyze(c)}>{rechecking?.id===c.id?<LoaderCircle className="spin" size={15}/>:<RefreshCw size={15}/>}<span>{c.label} · {date(c.created)}撮影<br/>{rechecking?.id===c.id?`この記録の${c.frames.length}枚を検索中…`:`仮確保 ${money(visionReserve(c.frames.length))}`}</span></Button>)}</div><p role="status" aria-live="polite" className="recheck-status">{rechecking?`「${rechecking.label}」（${date(rechecking.created)}撮影）の${rechecking.frames.length}枚を検索しています。`:''}</p></div>
<div className="return-panel"><div><span className="section-kicker">BACK TO HUMAN TIME</span><h2>見つけたら、何に戻りますか？</h2><p>検索時間の短縮だけでなく、その先の活動を記録します。</p></div><Input aria-label="戻りたい活動" placeholder="例：メンバーと新しい企画を考える" value={intent} onChange={e=>setIntent(e.target.value)} maxLength={160}/>{searchReceipt&&<label>実物を見つけた候補<Select value={confirmedResult} onValueChange={setConfirmedResult} disabled={!!busy||recorded}><SelectTrigger><SelectValue placeholder="確認できた候補を1件選択"/></SelectTrigger><SelectContent>{results.map((r,i)=><SelectItem key={i} value={String(i)}>{i+1}. {r.name} · 画像{r.frame+1} · {r.location||r.label}</SelectItem>)}</SelectContent></Select><p className="subtle">「実物を見つけた」を押した時だけ、選んだ候補の画像に検索語を保存します。</p></label>}<div className="inline"><Button disabled={!!busy||recorded||!!searchReceipt&&confirmedResult===''} onClick={()=>feedback(true)}><Check size={16}/>{recorded?'記録済み':'実物を見つけた'}</Button><Button variant="outline" disabled={!!busy||recorded} onClick={()=>feedback(false)}>見つからなかった</Button></div></div></>:<div className="search-empty"><span className="large-icon"><Search size={32}/></span><h2>「どこにあった？」を、聞かずに。</h2><p>{data.captures.length?'名前や見た目の特徴を入力して、撮影記録を探せます。':'最初の撮影を記録すると、ここから探せます。'}</p><div className="quick-queries">{['マイク','椅子','ケーブル'].map(q=><Button key={q} variant="outline" disabled={!!busy||!data.captures.length} onClick={()=>{setQuery(q);search(q);}}>{q}</Button>)}</div></div>}</TabsContent>
<TabsContent value="capture">{current?.isOwner&&<section className="capture-panel"><div className="section-heading"><div><span className="section-kicker">CAPTURE ONCE, SHARE THE CLUES</span><h2>空間をゆっくり見渡すように撮影</h2></div><span className="pill">動画90秒以内 / 写真12枚まで</span></div><p>人の顔や画面・書類を避けて撮影してください。文字や小物は近づいて撮ると手がかりが増えます。</p><div className="capture-drop"><Camera size={36}/><h3>動画・写真から、空間の記憶をつくる</h3><p>動画の各区間で鮮明さを比べ、最大12枚を選びます。すべての瞬間は確認できません。元動画は送信しません。</p><div className="inline"><Button disabled={!!busy} onClick={()=>input.current?.click()}><Camera size={17}/>動画を選ぶ</Button><Button disabled={!!busy} variant="outline" onClick={()=>photo.current?.click()}><ImageIcon size={17}/>写真を選ぶ</Button></div><input ref={input} type="file" accept="video/*" hidden onChange={e=>{choose(Array.from(e.target.files||[]));e.target.value='';}}/><input ref={photo} type="file" accept="image/*" multiple hidden onChange={e=>{choose(Array.from(e.target.files||[]));e.target.value='';}}/></div>
{busy==='extract'&&<div role="status"><Progress value={progress}/><p>画像を抽出しています… {progress}%</p></div>}{frames.length>0&&<><p className="subtle" role="status">保存予定：{frames.length}枚 · 補充候補：{selection.reserve.length}枚。{selection.reserve.length?'画像を除外すると、未使用の候補から補充します。補充された画像も確認してください。':'補充候補はありません。除外すると保存枚数が減ります。'}</p><div className="filmstrip">{frames.map((f,i)=><div key={i}><img src={f.data} alt={`保存前の確認画像${i+1}`}/><span>{i+1} · {f.time.toFixed(1)}秒</span><Button size="icon" variant="secondary" aria-label={`画像${i+1}を除外`} disabled={!!busy||!!captureId} onClick={()=>setSelection(v=>excludeAndRefill(v,i))}><Trash2 size={14}/></Button></div>)}</div><div className="form-fields"><label>撮影場所<Input placeholder="例：共有スペース・窓側" value={label} onChange={e=>setLabel(e.target.value)} maxLength={80} disabled={!!captureId}/></label><label>撮影日時（実際の日時を確認）<Input type="datetime-local" value={shotAt} onChange={e=>setShotAt(e.target.value)} disabled={!!captureId}/></label><label>補足メモ（任意）<Input placeholder="例：黒いマイクは窓際の机の上" value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500} disabled={!!captureId}/></label></div><Button onClick={save} disabled={!!busy||!label.trim()||!shotAt||saving}>{busy==='analyze'?<><LoaderCircle className="spin"/>AIで手がかりを解析中…</>:<><ScanLine size={17}/>{data.aiReady?'保存してAI解析':'撮影とメモを保存'}</>}</Button><p className="subtle">{data.aiReady?`この${frames.length}枚の解析は最大${money(visionReserve(frames.length))}を仮確保し、実際の使用量で精算します。` :'AI未接続です。入力したメモで検索できます。接続後、下の一覧から解析できます。'}</p></>}</section>}
<div className="results-heading"><h2>共有された撮影記録</h2><Button variant="ghost" onClick={()=>run('refresh',async()=>{await load();})} disabled={!!busy}><RefreshCw size={15}/>更新</Button></div>{!data.captures.length&&<p className="subtle">まだ撮影記録はありません。</p>}<div className="capture-list">{data.captures.map(c=><article key={c.id}><button className="capture-thumb" onClick={()=>{setEditLabel(c.label);setEditNotes(c.objects.find(o=>o.source==='手動')?.name||'');setSelected({name:c.label,label:c.label,created:c.created,capture:c.id,canEdit:c.canDelete,image:c.frames[0]?.id,description:'保存された撮影画像',location:'',frame:0});}}><img src={imageUrl(c.frames[0]?.id)} alt={c.label}/></button><div><h3>{c.label}</h3><p>{date(c.created)} · {c.frames.length}枚 · {c.objects.length}件の手がかり</p><small>{c.mode==='ai'?'AI解析済み':'AI未解析'} · 解析時の仮確保 {money(visionReserve(c.frames.length))}</small></div><div className="capture-buttons">{current?.isOwner&&<Button variant="outline" disabled={!!busy||!data.aiReady} onClick={()=>run('analyze',async()=>{const r=await post({action:'analyze',space,capture:c.id});setNotice(`${r.objects.length}件を解析しました。概算 ${money(r.cost)}`);await load();})}>{busy==='analyze'?<LoaderCircle className="spin" size={15}/>:<ScanLine size={15}/>}解析</Button>}{c.canDelete&&<AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="icon" aria-label={`${c.label}を削除`} disabled={!!busy}><Trash2 size={16}/></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogTitle>この撮影記録を削除しますか？</AlertDialogTitle><AlertDialogDescription>画像と解析結果を削除します。共有メンバーも閲覧できなくなります。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>戻る</AlertDialogCancel><AlertDialogAction onClick={()=>run('delete',async()=>{await post({action:'delete',space,capture:c.id});await load();setResults(null);})}>削除する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</div></article>)}</div></TabsContent>
<TabsContent value="share"><section className="share-panel"><span className="large-icon"><Users size={36}/></span><span className="section-kicker">SHARED SPATIAL MEMORY</span><h2>撮った人以外も、同じ記録から探せる。</h2><p>招待リンクを開くと、アカウントを作らずに、<br/>このスペースの撮影記録を閲覧・検索できます。</p><p className="pill">閲覧・検索：招待リンクを持つ人 / 編集・削除：作成者</p>{data.invite?<><label>招待コード</label><div className="invite-code"><code>{data.invite}</code><Button variant="outline" onClick={()=>run('copy',async()=>{await navigator.clipboard.writeText(location.origin+'/#invite='+data.invite);setNotice('招待リンクをコピーしました。');})}><Copy size={16}/>招待リンク</Button></div><p className="subtle">リンクを転送された人も閲覧できます。コードを変更すると、以前のリンクと閲覧セッションは無効になります。</p><Button variant="ghost" disabled={!!busy} onClick={()=>run('rotate',async()=>{await post({action:'rotate',space});await load();setNotice('新しい参加コードを発行しました。');})}>招待リンクを無効化・再発行</Button></>:<p>招待リンクは作成者から受け取ってください。</p>}{current?.isOwner&&<div className="api-settings"><h3>組織の初期設定・変更</h3><p>この組織専用の設定です。設定を保存しても、管理リンク・招待リンク・撮影記録は変わりません。</p><label>組織・スペース名<Input value={orgName} onChange={e=>setOrgName(e.target.value)} maxLength={80} placeholder="例：株式会社○○ 開発部"/></label><label>AI利用上限（米ドル・累計）<Input type="number" min="0" max={data.budget.cap} step="0.01" value={budgetInput} onChange={e=>setBudgetInput(e.target.value)}/></label><p className="subtle">現在の利用額：{money(data.budget.total)}。設定可能な上限：{money(data.budget.cap)}。0にするとAI処理を停止します。上限の変更で利用額はリセットされません。</p><Button disabled={!!busy||!orgName.trim()||budgetInput===''} onClick={()=>run('settings',async()=>{await post({action:'settings',space,name:orgName,budgetLimit:Number(budgetInput)});await load();setNotice('組織設定を保存しました。');})}>組織設定を保存</Button></div>}{current?.isOwner&&<div className="api-settings"><h3>AI解析の接続（作成者のみ）</h3><p>この組織のOpenAI APIキーを登録すると、AI解析を利用できます。未設定のままでも保存・閲覧・手動メモ検索を利用できます。キーは暗号化して保存し、閲覧者へ返しません。</p><Input type="password" autoComplete="off" aria-label="OpenAI APIキー" placeholder={data.aiReady?'登録済み（変更する場合のみ入力）':'未設定・空欄のまま利用開始できます'} value={apiInput} onChange={e=>setApiInput(e.target.value)}/><Button disabled={!!busy||!apiInput} onClick={()=>run('setkey',async()=>{await post({action:'setkey',key:apiInput});setApiInput('');await load();setNotice('APIキーを保存しました。撮影記録の解析で接続を確認できます。');})}>APIキーを保存</Button></div>}<div className="share-security"><ShieldCheck/><p>画像の取得時も、招待リンクまたは管理用リンクの権限を確認します。<br/>検索結果は撮影時点の手がかりです。隠れた物や撮影後の移動は把握できません。</p></div></section></TabsContent>
<TabsContent value="impact"><section className="impact-header"><span className="section-kicker">WHAT COMES AFTER FINDING?</span><h2>探した先に、どんな時間が生まれるか。</h2><p>「実物を見つけた」の回答と、本人が戻りたい活動の記録です。時間短縮やHuman Timeの増加を自動で証明する数値ではありません。</p></section><div className="impact-stats"><div><span>体験の回答</span><strong>{data.feedback.length}<small>件</small></strong></div><div><span>実物を見つけた</span><strong>{data.feedback.filter(f=>f.found).length}<small>件</small></strong></div><div><span>見つからなかった</span><strong>{data.feedback.filter(f=>!f.found).length}<small>件</small></strong></div></div><div className="intent-list">{data.feedback.length?data.feedback.map((f,i)=><article key={i}><span className={f.found?'found-tag':'notfound-tag'}>{f.found?'見つけた':'見つからなかった'}</span><h3>{f.intent||'戻りたい活動は未入力'}</h3><p>{date(f.created)} · 検索開始から回答まで {Math.round(f.seconds)}秒</p></article>):<div className="empty-state"><Clock size={32}/><h3>これから集まる、人の時間。</h3><p>検索後に感想を記録すると、ここに表示されます。</p></div>}</div><div className="definition"><div><h3>Mechanical Time</h3><p>置き場所を思い出す、知っている人に聞く、空間を探し回るための時間。</p></div><div><h3>Human Time</h3><p>本人が自らの意思で考え、感じ、向き合い、より良い未来をつくろうとする時間。</p></div></div></TabsContent></Tabs>}
<footer>ありか · Human Time Hackathon <span>テーマ2：人間が覚えておく仕事をなくす</span></footer></main></div>
<Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="evidence-dialog">{selected&&<><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.label} · {date(selected.created)}の記録。枠はAIによる概略位置です。</DialogDescription>{selectedCapture&&<section className="saved-images"><h3>保存された画像（{selectedCapture.frames.length}枚）</h3><p className="subtle">{selectedCapture.mode==='ai'?'AI解析済みの撮影記録です。':'AI未解析の撮影記録です。'}画像を選ぶと下に拡大表示します。</p>{error&&<p role="alert" className="message error">{error}</p>}<div className="saved-image-grid">{selectedCapture.frames.map((f,i)=><div key={f.id} className="saved-image-item"><button className="saved-image-thumb" aria-label={`画像${i+1}を拡大`} aria-pressed={selected.image===f.id} onClick={()=>setSelected((v:any)=>({...v,image:f.id}))}><img src={imageUrl(f.id)} loading="lazy" alt={`保存画像${i+1}`}/><span>{i+1} · {f.time.toFixed(1)}秒</span></button><AlertDialog><AlertDialogTrigger asChild><Button variant="outline" size="sm" disabled={!!busy||selectedCapture.frames.length<=1}><Trash2 size={14}/>画像{i+1}を削除</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogTitle>画像{i+1}を削除しますか？</AlertDialogTitle><AlertDialogDescription>この画像と、対応するAIの検索情報を削除します。共有利用者も閲覧できなくなります。元に戻せません。保存後の画像は自動補充されません。</AlertDialogDescription><img className="delete-image-preview" src={imageUrl(f.id)} alt={`削除する画像${i+1}`}/><AlertDialogFooter><AlertDialogCancel>戻る</AlertDialogCancel><AlertDialogAction onClick={()=>deleteFrame(selectedCapture,f.id)}>この画像を削除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>)}</div>{selectedCapture.frames.length===1&&<p className="subtle">最後の1枚です。すべて削除する場合は、記録一覧から撮影記録全体を削除してください。</p>}</section>}<div className="evidence-image"><img src={imageUrl(selected.image)} alt={`${selected.name}の根拠画像`}/>{selected.box&&<span className="object-box" style={{left:selected.box[0]*100+'%',top:selected.box[1]*100+'%',width:(selected.box[2]-selected.box[0])*100+'%',height:(selected.box[3]-selected.box[1])*100+'%'}}/>}</div><p>{selected.location} {selected.description}</p><p className="subtle">撮影後の移動や、完全に隠れた物は確認できません。</p>{selected.canEdit&&<div className="edit-record"><label>撮影場所<Input value={editLabel} onChange={e=>setEditLabel(e.target.value)}/></label><label>補足メモ<Input value={editNotes} onChange={e=>setEditNotes(e.target.value)}/></label><Button disabled={!!busy||!editLabel.trim()} onClick={()=>run('edit',async()=>{await post({action:'edit',space,capture:selected.capture,label:editLabel,notes:editNotes});await load();setSelected(null);setResults(null);setNotice('記録を更新しました。');})}>変更を保存</Button></div>}</>}</DialogContent></Dialog>
</div>;}
